<?php
class BillmateConfigForm
{
    /**
     * @var string
     */
    protected $module_name = 'billmategateway';

    /**
     * @var array;
     */
    protected $statuses_prepared = [];

    /**
     * BillmateConfigForm constructor.
     *
     * @param $statuses_prepared
     */
    public function __construct($statuses_prepared)
    {
        $this->statuses_prepared = $statuses_prepared;
    }

    public function getSettingsForm()
    {
        $settings       = array();

        $settings['billmateid'] = array(
            'name'     => 'billmateId',
            'required' => true,
            'type'     => 'text',
            'label'    => $this->l('Billmate ID'),
            'desc'     => $this->l('The Billmate ID from Billmate Online'),
            'value'    => Configuration::get('BILLMATE_ID'),
        );

        $settings['billmatesecret'] = array(
            'name'     => 'billmateSecret',
            'required' => true,
            'type'     => 'text',
            'label'    => $this->l('Secret'),
            'desc'     => $this->l('The secret key from Billmate Online'),
            'value'    => Configuration::get('BILLMATE_SECRET')
        );

        $reference = array('orderid' => $this->l('Order ID'),'reference' => $this->l('Reference ID'));
        $settings['sendorderreference'] = array(
            'name'     => 'sendOrderReference',
            'required' => true,
            'type'     => 'select',
            'label'    => $this->l('Order id used by Billmate'),
            'desc'     => '',
            'value'    => Configuration::get('BILLMATE_SEND_REFERENCE') ? Configuration::get('BILLMATE_SEND_REFERENCE') : 'orderid',
            'options' => $reference
        );

        $activate_status      = Configuration::get('BILLMATE_ACTIVATE');
        $settings['activate'] = array(
            'name'     => 'activate',
            'required' => true,
            'type'     => 'checkbox',
            'label'    => $this->l('Activate Invoices'),
            'desc'     => $this->l('Activate Invoices with a certain status in Billmate Online'),
            'value'    => $activate_status
        );

        $settings['activateStatuses'] = array(
            'name'     => 'activateStatuses[]',
            'id'       => 'activation_options',
            'required' => true,
            'type'     => 'multiselect',
            'label'    => $this->l('Order statuses for automatic order activation in Billmate Online'),
            'desc'     => '',
            'value'    => (Tools::safeOutput(Configuration::get('BILLMATE_ACTIVATE_STATUS'))) ? unserialize(Configuration::get('BILLMATE_ACTIVATE_STATUS')) : 0,
            'options'  => $this->statuses_prepared
        );
        $credit_status      = Configuration::get('BILLMATE_CANCEL');
        $settings['credit'] = array(
            'name'     => 'credit',
            'required' => true,
            'type'     => 'checkbox',
            'label'    => $this->l('Credit Invoices'),
            'desc'     => $this->l('Credit Invoices with a certain status in Billmate Online'),
            'value'    => $credit_status
        );

        $settings['creditStatuses'] = array(
            'name'     => 'creditStatuses[]',
            'id'       => 'credit_options',
            'required' => true,
            'type'     => 'multiselect',
            'label'    => $this->l('Order statuses for automatic order credit in Billmate Online'),
            'desc'     => '',
            'value'    => (Tools::safeOutput(Configuration::get('BILLMATE_CANCEL_STATUS'))) ? unserialize(Configuration::get('BILLMATE_CANCEL_STATUS')) : 0,
            'options'  => $this->statuses_prepared
        );
        $settings['getaddress'] = array(
            'name' => 'getaddress',
            'type' => 'checkbox',
            'label' => $this->l('Activate GetAddress'),
            'desc' => $this->l('Activate get address by social security number to speed up the checkout process.'),
            'value' => Configuration::get('BILLMATE_GETADDRESS')
        );
        $message_status      = Configuration::get('BILLMATE_MESSAGE');
        $settings['message'] = array(
            'name'     => 'message',
            'required' => true,
            'type'     => 'checkbox',
            'label'    => $this->l('Activate Messages on the invoice'),
            'desc'     => $this->l('Add prestashop message to the invoice generated by Billmate'),
            'value'    => $message_status
        );


        $settings['logo'] = array(
            'name' => 'logo',
            'type' => 'text',
            'label' => $this->l('Logo to be displayed in the invoice'),
            'desc' => $this->l('Enter the name of the logo (shown in Billmate Online). Leave empty if you only have one logo.'),
            'value' => Configuration::get('BILLMATE_LOGO')
        );
        return $settings;
    }

    /**
     * @param $string
     *
     * @return string
     */
    public function l($string)
    {
        return Translate::getModuleTranslation($this->module_name, $string, $this->module_name);

    }
}